# Generated by Django 3.0.4 on 2020-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('personal_email', models.EmailField(max_length=254)),
                ('up_email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.BigIntegerField(blank=True, null=True)),
                ('college', models.CharField(choices=[('CAL', 'College of Arts and Letters'), ('CFA', 'College of Fine Arts'), ('CHK', 'College of Human Kinetics'), ('CMC', 'College of Mass Communication'), ('AIT', 'Asian Institute of Tourism'), ('CBA', 'College of Business Administration'), ('ECON', 'School of Economics'), ('SOLAIR', 'School of Labor and Industrial Relations'), ('NCPAG', 'National College of Public Administration and Governance'), ('ASP', 'Archaeological Studies Program'), ('ARKI', 'College of Architecture'), ('ENGG', 'College of Engineering'), ('CHE', 'College of Home Economics'), ('CS', 'College of Science'), ('SLIS', 'School of Library and Information Studies'), ('STAT', 'School of Statistics'), ('AC', 'Asian Center'), ('EDUK', 'College of Education'), ('IIS', 'Institute of Islamic Studies'), ('LAW', 'College of Law'), ('CSSP', 'College of Social Sciences and Philosophy'), ('CSWCD', 'College of Social Work and Child Development'), ('UPOU', 'UP Open University'), ('O', 'Other')], max_length=8)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photography_field', models.CharField(blank=True, max_length=256)),
                ('facebook', models.CharField(blank=True, max_length=64, verbose_name='Facebook username')),
                ('twitter', models.CharField(blank=True, max_length=64, verbose_name='Twitter username (without @)')),
                ('instagram', models.CharField(blank=True, max_length=64, verbose_name='Instagram username (without @)')),
                ('website', models.CharField(blank=True, max_length=256)),
                ('picture_url', models.URLField(blank=True)),
                ('committee', models.CharField(choices=[('X', 'Executive'), ('E', 'Externals'), ('I', 'Internals'), ('P', 'Promos'), ('L', 'Logistics'), ('F', 'Finance'), ('A', 'Alumni')], max_length=1)),
            ],
        ),
    ]
