# Generated by Django 3.1.1 on 2020-10-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200425_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture_url',
            field=models.CharField(max_length=255),
        ),
    ]
