# Generated by Django 3.1.1 on 2020-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201014_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='executive_committee_position',
            field=models.CharField(blank=True, choices=[('', ''), ('PRE', 'President'), ('VPE', 'Vice President for External Affairs'), ('VPI', 'Vice President for Internal Affairs'), ('SG', 'Secretary-General'), ('EOP', 'Executive Officer for Promotions and Documentation'), ('EOL', 'Executive Officer for Logistics'), ('CE', 'Chancellor of the Exchequer')], max_length=3),
        ),
    ]
