# Generated by Django 3.1.1 on 2020-10-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_member_executive_committee_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-committee', 'last_name', 'first_name']},
        ),
    ]
