# Generated by Django 3.0.4 on 2020-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200322_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=64, verbose_name='Facebook username'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Instagram username (without @)'),
        ),
        migrations.AddField(
            model_name='member',
            name='photography_field',
            field=models.TextField(default='Portrait'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='twitter',
            field=models.CharField(blank=True, max_length=64, verbose_name='Twitter username (without @)'),
        ),
        migrations.AddField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
